@startuml
!include ../template/templateContextC4.puml

title Контекстная диаграмма первоночального состоятия системы

Person(user, "Пользователь", "Владелец умного дома, управляет отоплением и запрашивает данные о температуре")
Person(worker, "Специалист", "Подключает новых пользователей, настраивает систему на месте")

System(api, "Api", "REST API для управления датчиками отопления и мониторинга температуры. Предоставляет CRUD операции для датчиков")

SystemDb(postgres, "PostgreSql", "База данных для хранения информации о датчиках")

System_Ext(temperatureAPI, "TemperatureApi", "Внешний сервис для получения актуальных данных о температуре в реальном времени")

Rel(user, api, "Управляет отоплением, запрашивает температуру")
Rel(worker, api, "Настраивает датчики, подключает пользователей")
Rel(api, postgres, "Читает и записывает данные о датчиках")
Rel(api, temperatureAPI, "Запрашивает актуальную температуру")

@enduml
