@startuml
!include ../template/templateContainerC4.puml

title Контекстная диаграмма целевой микросервисной архитектуры

Person(user, "Пользователь", "Владелец умного дома - самостоятельно управляет всеми функциями системы")

System_Boundary(smartHomeSystem, "Экосистема умного дома") {
    System(mobileApp, "Мобильное приложение", "Пользователь взаимодействует с системой через мобильное приложение")
    System(apiGateway, "API-шлюз", "Единая точка входа для всех клиентских запросов. Обеспечивает аутентификацию, авторизацию и маршрутизацию")
    System(userManagement, "Сервис управления пользователями", "Управление подписками и аутентификацией пользователей")
    System(deviceManagement, "Сервис менеджмента устройств", "Регистрация и удаление устроиств в системе. Список подключенных устройств пользователя")
    System(deviceControl, "Сервис упраления устройствами", "Вкл/выкл устройств: отопление, свет, ворота и другое")
    System(dataHub, "Сервис данныхх устройств", "Сбор, хранение и предоставление данных от устройств")
    System(automation, "Сервис автоматизации сценариев", "Создание и выполнение сценариев автоматизации для всех устройств")
    System(integration, "Сервис интеграции партнерских устройств", "Интеграция с устройствами партнеров по стандартным протоколам")
    System(notification, "Сервис нотификаций", "Отправка уведомлений пользователям")
    SystemQueue(signalBroker, "Сервис обмена событиями", "Асинхронная обработка событий между микросервисами")
}

SystemDb_Ext(userDatabase, "БД пользователей и подписок", "Тут хранятся данные о пользователях и их уровне подписки")
SystemDb_Ext(deviceDatabase, "БД устройств", "Тут хранятся данные о подлюченных устройствах")
SystemDb_Ext(dataDB, "БД данных устройств", "Хранилище полученных данных от устройств")
SystemDb_Ext(automationDatabase, "БД сценариев и правил", "Тут хранятся сценарии автоматизации")

System_Ext(partnerDevices, "Устройства партнеров", "Умные устройства сторонних производителей, подключенные по стандартным протоколам к системе")
System_Ext(temperature, "Внешний сервис температуры", "Внешний сервис для получения данных о температуре")

Rel(user, mobileApp, "пользователь взаимодействует с системой по средствам мобильного приложения")
Rel(mobileApp, apiGateway, "Управляет устройствами, настраивает сценарии, просматривает данные с устройств")

Rel(apiGateway, userManagement, "Проверка аутентификации и авторизации")
Rel(apiGateway, deviceManagement, "Получение списка устройств пользователя")
Rel(apiGateway, deviceControl, "Отправка команд управления устройствами")
Rel(apiGateway, dataHub, "Запрос данных")
Rel(apiGateway, automation, "Управление сценариями")

Rel(deviceControl, deviceManagement, "Проверка существования и прав доступа к устройству")
Rel(automation, deviceControl, "Выполнение команд в сценариях")
Rel(automation, dataHub, "Чтение данных для условий сценариев")

Rel(deviceControl, signalBroker, "Публикует события о выполнении команд")
Rel(dataHub, signalBroker, "Публикует события")
Rel(signalBroker, automation, "Доставляет события для триггеров сценариев")
Rel(signalBroker, notification, "Доставляет события для уведомлений")
Rel(integration, signalBroker, "Публикует телеметрию от устройств партнеров")
Rel(signalBroker, dataHub, "Доставляет телеметрию для сохранения")

Rel(integration, partnerDevices, "Подключение и управление устройствами партнеров")
Rel(dataHub, temperature, "Получение данных о температуре в рантайме")

Rel(userManagement, userDatabase, "Читает и записывает данные пользователей")
Rel(deviceManagement, deviceDatabase, "Читает и записывает данные об устройствах")
Rel(dataHub, dataDB, "Читает и записывает телеметрию")
Rel(automation, automationDatabase, "Читает и записывает сценарии")

Rel(notification, user, "Отправляет уведомления")

@enduml
